### ISSUE TITLE
Cannot install via haxelib install

### ISSUE THREAD

**Issue by kevansevans** [nanjizal/Trilateral#1]
As title says, haxelib does not recognize trilateral as a valid project.

**Comment by nanjizal** [comment]
Hi kevensevans it's not on haxelib yet, it's still in work in progress.

You can check it out via      
```haxelib git trilateral https://github.com/nanjizal/Trilateral.git```

or you clone it locally and use haxelib to install a 'local' version along the lines of:
```git clone https://github.com/nanjizal/Trilateral.git```
```cd trilateral/src```
```haxe rebuildLocalLib.hxml```

Current Aspects that need work before I consider putting the project on haxelib:

* Arc / Pie drawing code parameters are inconsistency, fixing requires major changes to line corner implementation in Contour. ( It's a x, y flip negative thing probably as I tested in WebGL initially,  I suspect justTriangles does not have this problem, but seem CLOCKWISE is anti and angles have a PI related offset, still works but confusing ).  PUTTING OFF FIXING AS IT MAYBE HEADACHE.

* Elliptical Arc algorithm lifted from an online source has been refactored to remove calculations per point putting them in the setup, it also uses my radian abstractions but it is unfortunately broken it draws arcs but the begin and end and interpretation of the 'sweep' and 'large' are broken.  It is not yet connected to svg path parsing code.  It would be nice to fix it but still unsure about adding it to path parsing as it's not a light algorithm ( crazy svg people ) and requires more parameters than my parser currently allows and I don't want it to negatively impact normal parsing speed. HAVE FOUGHT WITH RECENTLY, MAY LEAVE FOR MOMENT.

* Example do not yet include gradient or image fill examples ( theory has been tested in my other repositories ), some code is implemented for gradients. Image fill should be feasible without changes. A demo is needed for Kha and WebGL before I am sure on the Triangle Gradient Abstract. AIM TO DO SOON.

* Further consideration is required in relation to Fill libraries and best integration, perhaps adding integration of hxPolyK ( which is on haxelib but out of date ), and poly2trihx.  One aspect that is troublesome is that poly2trihx gets upset with repeat coordinate end shapes. It would be nice to lift the poly simplifier from hxDaedalus for use with fills. Tricky because it would be annoying to have them as dependancy.  I may need to hack poly2trihx to be more tolerant of repeat points not sure it's currently MIT though.  MIGHT DO

* I am considering how triangle data is stored, possibly changing it to draw directly on the buffer to reduce transfer of Array and Object data which is probably heavier than I would like, but that require perhaps closer coupling with target, perhaps horrible singleton and may need compiler switches if the library is to work with differing triangle draw methods. CONSIDERING MAY CREATE A BRANCH.

* Curve Accuracy is currently not linked to dimensions I am unsure if this is a user problem?

* Would like to add some more basic useful Shapes like Arrows. SHOULD DO SOON.

* Need to create examples of hitTest and perhaps add some methods see my tetris clone for concepts. SHOULD DO SOON.

* Not sure I remember my Haxelib password!! :)

* Need Dox added.

While the code is fairly stable and useful in it's current form I am not sure it's ready for Haxelib, I rarely put code on haxelib, but I am sure you could use it in production provided you realise it's likely to change.
